"""init

Revision ID: c3ab89b0817f
Revises: 
Create Date: 2026-04-19 22:36:00.623510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3ab89b0817f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('centroid', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_keywords', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('dominant_domains', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('faiss_index_id', sa.Integer(), nullable=True),
    sa.Column('centroid_version', sa.String(length=64), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('avg_relevance_score', sa.Float(), nullable=True),
    sa.Column('algorithm_meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_recomputed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_clusters')),
    sa.UniqueConstraint('faiss_index_id', name=op.f('uq_opportunity_clusters_faiss_index_id'))
    )
    op.create_index(op.f('ix_opportunity_clusters_id'), 'opportunity_clusters', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'RESEARCHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('academic_level', sa.Enum('BACHELOR', 'MASTER', 'PHD', 'POSTDOC', 'PROFESSOR', name='academiclevel'), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INTERNSHIP', 'RESEARCH_PROJECT', 'SCHOLARSHIP', 'FELLOWSHIP', 'CERTIFICATION', 'WEBINAR', 'ONLINE_COURSE', 'POSTDOC', 'VISITING_PROFESSOR', name='opportunitytype'), nullable=False),
    sa.Column('domain', sa.Enum('AI', 'DATA_SCIENCE', 'MACHINE_LEARNING', 'COMPUTER_VISION', 'NLP', 'ROBOTICS', 'CYBERSECURITY', 'SOFTWARE_ENGINEERING', 'DATA_ENGINEERING', 'BIOINFORMATICS', 'OTHER', name='opportunitydomain'), nullable=False),
    sa.Column('level', sa.Enum('BACHELOR', 'MASTER', 'PHD', 'POSTDOC', 'PROFESSOR', 'ALL', name='opportunitylevel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DRAFT', 'ARCHIVED', name='opportunitystatus'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('location_type', sa.Enum('REMOTE', 'ONSITE', 'HYBRID', 'UNKNOWN', name='opportunitylocationtype'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('stipend_amount', sa.Float(), nullable=True),
    sa.Column('stipend_currency', sa.String(length=10), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_cluster_assignment', sa.Boolean(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('scraper_type', sa.Enum('STATIC', 'DYNAMIC', name='scrapertype'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['opportunity_clusters.id'], name=op.f('fk_opportunities_cluster_id_opportunity_clusters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('url', name=op.f('uq_opportunities_url'))
    )
    op.create_index(op.f('ix_opportunities_cluster_id'), 'opportunities', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_opportunities_country'), 'opportunities', ['country'], unique=False)
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_domain'), 'opportunities', ['domain'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_level'), 'opportunities', ['level'], unique=False)
    op.create_index(op.f('ix_opportunities_needs_cluster_assignment'), 'opportunities', ['needs_cluster_assignment'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True, comment='Null for system notifications not tied to a specific opportunity.'),
    sa.Column('type', sa.Enum('NEW_OPPORTUNITY', 'DEADLINE_REMINDER', 'NEW_RECOMMENDATION', 'CLUSTER_UPDATE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ARCHIVED', name='notificationstatus'), nullable=False),
    sa.Column('is_email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_notifications_opportunity_id_opportunities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_opportunity_id'), 'notifications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True, comment="Position in the user's ranked recommendation list (1 = best)."),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCORED', 'DISMISSED', 'APPLIED', name='recommendationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_recommendations_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_recommendations_user_opportunity')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_opportunity_id'), 'recommendations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_opportunity_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_opportunity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_needs_cluster_assignment'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_level'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_domain'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_country'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_cluster_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_opportunity_clusters_id'), table_name='opportunity_clusters')
    op.drop_table('opportunity_clusters')
    # ### end Alembic commands ###
